const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs');
const {JSDOM}=require(process.env.JSDOM_MODULE||'jsdom');
const source=fs.readFileSync(__dirname+'/../../app/src/main/assets/care-questionnaires.js','utf8');
const tick=()=>new Promise(r=>setImmediate(r));
const fixture={id:'assignment-a',patient_id:'patient-a',clinician_id:'doctor-a',active:true,title:'Controllo del medico',version_label:'1',created_at:'2026-10-06T10:00:00Z',questions:[{id:'symptom',label:'Hai sintomi?',type:'choice',required:true,options:['No','Sì, ora','Sì, ieri']},{id:'note',label:'Una nota per il medico?',type:'text',required:false}]};
function setup(rows=[fixture]){
 const dom=new JSDOM('<main id="content"></main>',{url:'https://example.invalid',runScripts:'outside-only'}),w=dom.window,calls=[];
 w.state={tab:'assignedQuestionnaires',session:{user:{id:'patient-a'}},selectedCareDoctor:'doctor-a',careDoctors:[{clinician_id:'doctor-a',profiles:{full_name:'Dottore Demo'}}]};
 w.content=w.document.getElementById('content');w.esc=x=>String(x??'').replace(/[<>&"]/g,'');w.msg=x=>String(x);w.patientView=()=>{};w.mediSpeakCloud=x=>{w.spoken=x};
 w.voiceText=x=>String(x||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[.!?,;:]/g,' ').replace(/\s+/g,' ').trim();
 w.MediTurn={stop(){},ask(text,options){w.turn={text,...options}}};
 w.sb={from(table){return {select(){return this},eq(){return this},order:async()=>({data:rows}),maybeSingle:async()=>({data:null})}},rpc:async(name,args)=>{calls.push({name,args});return {error:null}}};
 w.eval(source);return {w,calls,close:()=>w.close()};
}
test('without an assignment no questionnaire or voice form is offered',async()=>{const x=setup([]);await x.w.patientAssignedQuestionnaires();assert.equal(x.w.document.querySelectorAll('form').length,0);assert.match(x.w.content.textContent,/Nessun questionario assegnato/);assert.equal(x.calls.length,0);x.close()});
test('only active assignments for this patient and selected doctor are shown',async()=>{const x=setup([fixture,{...fixture,id:'other',patient_id:'other'},{...fixture,id:'closed',active:false},{...fixture,id:'other-doctor',clinician_id:'other'}]);await x.w.patientAssignedQuestionnaires();assert.equal(x.w.document.querySelectorAll('form').length,1);assert.match(x.w.content.textContent,/Dottore Demo/);x.close()});
test('voice answers fill the assigned form and require explicit final confirmation',async()=>{const x=setup(),w=x.w;await w.patientAssignedQuestionnaires();w.document.querySelector('.cqVoiceStart').click();assert.match(w.turn.text,/Hai sintomi/);w.turn.answer('sì');assert.equal(w.document.querySelector('select').value,'');assert.equal(x.calls.length,0);w.document.querySelector('.cqVoiceStart').click();w.turn.answer('No');assert.equal(w.document.querySelector('select').value,'No');assert.match(w.turn.text,/Una nota/);w.turn.answer('Oggi sto meglio');assert.equal(w.document.querySelector('textarea').value,'Oggi sto meglio');assert.equal(x.calls.length,0);w.turn.answer('sì');assert.equal(x.calls.length,0);w.document.querySelector('.cqVoiceStart').click();w.turn.answer('confermo invio');await tick();assert.equal(x.calls.length,1);assert.equal(x.calls[0].name,'submit_care_questionnaire');assert.equal(x.calls[0].args.p_assignment,fixture.id);assert.equal(x.calls[0].args.p_answers.note,'Oggi sto meglio');x.close()});
test('late voice results cannot fill another question or send after an account change',async()=>{const x=setup(),w=x.w;await w.patientAssignedQuestionnaires();w.document.querySelector('.cqVoiceStart').click();const old=w.turn;w.document.querySelector('select').value='No';w.document.querySelector('.cqVoiceNext').click();old.answer('Sì, ora');assert.equal(w.document.querySelector('select').value,'No');const next=w.turn;w.state.session.user.id='another-patient';next.answer('risposta precedente');assert.equal(w.document.querySelector('textarea').value,'');assert.equal(x.calls.length,0);x.close()});
test('urgent answers are spoken and pause the voice sequence',async()=>{const x=setup([{...fixture,questions:[{...fixture.questions[0],alert_values:['Sì, ora']},fixture.questions[1]]}]),w=x.w;await w.patientAssignedQuestionnaires();w.document.querySelector('.cqVoiceStart').click();w.turn.answer('Sì, ora');assert.match(w.spoken,/112/);assert.equal(w.document.querySelector('.notice.error').hidden,false);assert.equal(x.calls.length,0);x.close()});
