begin;
create temporary table beta52_fixture as select gen_random_uuid() patient,gen_random_uuid() other_patient,gen_random_uuid() doctor,gen_random_uuid() other_doctor,gen_random_uuid() request;
grant select on beta52_fixture to authenticated;
insert into auth.users(id,raw_user_meta_data) select x.id,'{"full_name":"BETA52 TRANSIENT TEST"}'::jsonb from beta52_fixture f cross join lateral (values(f.patient),(f.other_patient),(f.doctor),(f.other_doctor)) x(id);
update public.profiles set role='Clinician' where id in (select doctor from beta52_fixture union all select other_doctor from beta52_fixture);
insert into public.patient_clinicians(patient_id,clinician_id) select patient,doctor from beta52_fixture union all select other_patient,other_doctor from beta52_fixture;
update public.patient_care_contacts c set primary_clinician_id=f.doctor from beta52_fixture f where c.patient_id=f.patient;
set local role authenticated;
do $$
declare f record; a jsonb; b jsonb; report uuid; rejected boolean:=false;
begin
 select * into f from beta52_fixture;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',f.patient,'role','authenticated')::text,true);
 a:=public.submit_interactive_checkin(f.request,'green','TEST FITTIZIO BETA52, nessun dato sanitario reale.',f.doctor,(now() at time zone 'Europe/Rome')::date);
 b:=public.submit_interactive_checkin(f.request,'green','TEST FITTIZIO BETA52, nessun dato sanitario reale.',f.doctor,(now() at time zone 'Europe/Rome')::date);
 assert (b->>'replayed')::boolean and a->>'message_id'=b->>'message_id','Replay mismatch';
 assert (select count(*)=1 from public.chat_messages where id=(a->>'message_id')::uuid),'Message absent';
 begin perform public.submit_interactive_checkin(gen_random_uuid(),'green','TEST FITTIZIO BETA52',f.other_doctor,(now() at time zone 'Europe/Rome')::date);
 exception when others then if sqlerrm='ACTIVE_LINK_REQUIRED' then rejected:=true;else raise;end if;end;
 assert rejected,'Unlinked recipient accepted';
 insert into public.medical_reports(patient_id,title,storage_path,uploaded_by) values(f.patient,'BETA52 synthetic metadata','beta52-test/no-file',f.doctor) returning id into report;
 assert (select uploaded_by=f.patient from public.medical_reports where id=report),'Sender forgery accepted';
 rejected:=false;
 begin update public.medical_reports set uploaded_by=f.doctor where id=report;
 exception when others then if sqlerrm='IMMUTABLE_REPORT_SENDER' then rejected:=true;else raise;end if;end;
 assert rejected,'Sender editable';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',f.other_patient,'role','authenticated')::text,true);
 assert not exists(select 1 from public.checkin_message_receipts where request_id=f.request),'Cross patient receipt exposure';
 assert not exists(select 1 from public.medical_reports where id=report),'Cross patient report exposure';
 rejected:=false;
 begin perform public.disconnect_my_clinician(f.doctor);
 exception when others then if sqlerrm='ACTIVE_LINK_REQUIRED' then rejected:=true;else raise;end if;end;
 assert rejected,'Cross patient disconnect accepted';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',f.patient,'role','authenticated')::text,true);
 perform public.disconnect_my_clinician(f.doctor);
 assert not exists(select 1 from public.patient_clinicians where patient_id=f.patient and clinician_id=f.doctor and active),'Disconnect ineffective';
 rejected:=false;
 begin perform public.submit_interactive_checkin(gen_random_uuid(),'green','TEST FITTIZIO BETA52',f.doctor,(now() at time zone 'Europe/Rome')::date);
 exception when others then if sqlerrm='ACTIVE_LINK_REQUIRED' then rejected:=true;else raise;end if;end;
 assert rejected,'Disconnected recipient accepted';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',f.doctor,'role','authenticated')::text,true);
 assert not exists(select 1 from public.patient_daily_checkins where id=(a->>'checkin_id')::uuid),'Revoked doctor reads checkin';
 assert not exists(select 1 from public.medical_reports where id=report),'Revoked doctor reads report';
end $$;
rollback;
select 'PASS: replay, recipient scope, provenance, isolation, disconnect and revocation; all fixtures rolled back' as beta52_database_test;
