const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require(process.env.JSDOM_MODULE||'jsdom');
const source=['patient-upgrade.js','patient-welcome.js'].map(n=>fs.readFileSync(__dirname+'/../../app/src/main/assets/'+n,'utf8')).join('\n');
const tick=()=>new Promise(r=>setImmediate(r));
function fixture(){const w=new JSDOM('<section class="daily-checkin-card">HOME ORIGINALE</section><div id="mediModal" class="hidden"><div id="mediAnswer"></div><span id="mediVoiceStatus"></span></div>',{url:'https://example.test',runScripts:'outside-only'}).window;let completedSpeech,turn,sent=0;const said=[];
 Object.assign(w,{state:{session:{user:{id:'p'},access_token:'fake'},profile:{role:'Patient'},tab:'home',careDoctors:[],lastGreetingAt:0},mediVoiceActive:false,mediSpeechOnDone:null,mediStopCloud:()=>{},mediSpeakCloud:(text,done)=>{said.push(text);completedSpeech=done;},loadCareDoctors:async()=>{},esc:s=>String(s||''),confirm:()=>true,patientHome:()=>{},dispatchChatPush:()=>{},AndroidBridge:{cancelMediTurn:()=>{},listenForMediTurn:(id,ms)=>turn={id,ms}},sb:{rpc:async()=>{sent++;return {data:{}};}}});
 w.eval(source);w.patientGemini=async()=>({provider:'gemini',followup:'none'});
 return {w,said,sent:()=>sent,answer:async text=>{assert.ok(completedSpeech,'Question must be read before listening');completedSpeech();w.onMeditalyMediTurnInput(turn.id,text);await tick();},heading:()=>w.document.querySelector('#ciStep h3')?.textContent};
}
test('spoken yes opens questionnaire; all questions read and auto-filled without sending',async()=>{const f=fixture();await f.w.startPatientWelcome('Mario');await f.answer('bene');assert.equal(f.w.document.querySelector('#interactiveCheckin'),null);await f.answer('sì');assert.match(f.heading(),/Rispetto a ieri/);await f.answer('meglio');assert.match(f.heading(),/disturbi/);await f.answer('no');assert.match(f.heading(),/farmaci/);await f.answer('Assunti come previsto');assert.match(f.heading(),/sonno/);await f.answer('Come al solito');assert.match(f.heading(),/misurato/);await f.answer('no');assert.match(f.heading(),/altro/);await f.answer('no');assert.ok(f.w.document.querySelector('#ciSend'));assert.equal(f.sent(),0);assert.equal(f.w.document.querySelector('#ciConsent'),null);assert.doesNotMatch(f.w.document.querySelector('#interactiveCheckin').textContent,/Gemini/);assert.equal(f.w.document.querySelector('.daily-checkin-card').textContent,'HOME ORIGINALE');f.w.close();});
test('tap on mood still requires questionnaire invitation',async()=>{const f=fixture();f.w.offerPatientQuestionnaire('yellow');assert.equal(f.w.document.querySelector('#interactiveCheckin'),null);await f.answer('no');assert.equal(f.w.document.querySelector('#interactiveCheckin'),null);assert.equal(f.sent(),0);assert.ok(f.w.document.querySelector('#mediModal').classList.contains('hidden'));f.w.close();});
