const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {JSDOM}=require(process.env.JSDOM_MODULE||'jsdom');
const source=fs.readFileSync(__dirname+'/../../app/src/main/assets/patient-welcome.js','utf8');
function setup({role='Administrator',api}={}){
 const dom=new JSDOM('<section class="daily-checkin-card">HOME ORIGINALE</section><div id="mediModal" class="hidden"><div id="mediAnswer"></div><div id="mediVoiceStatus"></div></div>',{url:'https://example.test',runScripts:'outside-only'}),w=dom.window;
 const calls=[],opened=[],speech=[];let done,turn;
 Object.assign(w,{state:{session:{user:{id:'test-patient'}},profile:{role},tab:'home',lastGreetingAt:0,homeVoicePending:true},activeCheckin:null,mediVoiceActive:false,mediStopCloud:()=>{},esc:s=>String(s),mediSpeakCloud:async(s,cb)=>{speech.push(s);done=cb;},patientGemini:async p=>{calls.push(p);return api?api(p):{provider:'gemini',followup:'impact'};},startInteractiveCheckin:async(...args)=>opened.push(args),AndroidBridge:{cancelMediTurn:()=>{},listenForMediTurn:(id,ms)=>{turn={id,ms};}}});
 w.eval(source);return {w,calls,opened,speech,done:()=>done?.(),turn:()=>turn,answer:text=>w.onMeditalyMediTurnInput(turn.id,text)};
}
test('automatic entry does not add or change home layout',async()=>{const f=setup(),home=f.w.document.querySelector('.daily-checkin-card'),before=home.outerHTML;await f.w.startPatientWelcome('Mario');assert.equal(home.outerHTML,before);assert.equal(f.w.document.querySelector('#patientWelcomeCard'),null);assert.equal(f.speech[0],'Ciao Mario, come stai oggi?');assert.equal(f.calls[0].mode,'welcome');f.done();assert.equal(f.turn().ms,2500);});
test('mood answer asks invitation, no questionnaire before yes',async()=>{const f=setup();await f.w.startPatientWelcome('Mario');await f.w.handleWelcomeReply('bene');assert.equal(f.opened.length,0);assert.equal(f.calls.length,1);assert.equal(f.speech.at(-1),'Ti va di rispondere a qualche domanda?');assert.equal(f.w.document.querySelector('#mediModal').classList.contains('hidden'),false);});
test('no returns home with no health data transmission or questionnaire',async()=>{const f=setup();await f.w.startPatientWelcome('Mario');await f.w.handleWelcomeReply('così così');await f.w.handleWelcomeReply('non ora');assert.equal(f.opened.length,0);assert.equal(f.calls.length,1);assert.ok(f.w.document.querySelector('#mediModal').classList.contains('hidden'));});
test('yes automatically uses Medi and opens questionnaire, with no opt-in control',async()=>{const f=setup();await f.w.startPatientWelcome('Mario');await f.w.handleWelcomeReply('così così');await f.w.handleWelcomeReply('sì');assert.equal(f.calls[1].mode,'checkin');assert.equal(f.opened[0][0],'yellow');assert.equal(f.opened[0][1].followup,'Quanto incide sulle tue attività quotidiane?');assert.equal(f.w.document.querySelector('input[type=checkbox]'),null);});
test('unrecognized mood is not clinically inferred and cannot start questionnaire',async()=>{const f=setup();await f.w.startPatientWelcome('Mario');await f.w.handleWelcomeReply('ho dolore forte');assert.equal(f.opened.length,0);assert.match(f.speech.at(-1),/bene, così così/);assert.equal(f.calls.length,1);});
test('late model answer cannot reopen questionnaire after pause',async()=>{let release;const f=setup({api:p=>p.mode==='checkin'?new Promise(r=>release=r):Promise.resolve({provider:'gemini'})});await f.w.startPatientWelcome('Mario');await f.w.handleWelcomeReply('sto male');const pending=f.w.handleWelcomeReply('sì');f.w.onMeditalyAppPause();release({followup:'impact'});await pending;assert.equal(f.opened.length,0);});
test('stale microphone result cannot answer the next voice turn',async()=>{const f=setup();await f.w.startPatientWelcome('Mario');f.done();const old=f.turn().id;f.answer('bene');f.done();assert.notEqual(f.turn().id,old);f.w.onMeditalyMediTurnInput(old,'sì');assert.equal(f.opened.length,0);assert.equal(f.calls.length,1);});
test('microphone starts only when speech is complete',async()=>{const f=setup();await f.w.startPatientWelcome('Mario');assert.equal(f.turn(),undefined);f.done();assert.ok(f.turn());});
