pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url = uri('vendor-maven'); metadataSources { mavenPom(); artifact(); ignoreGradleMetadataRedirection() } }
        google()
        mavenCentral()
    }
}
rootProject.name = "Meditaly"
include ':app'
