plugins {
    id 'com.android.application'
}

if (file('google-services.json').exists()) {
    apply plugin: 'com.google.gms.google-services'
}

android {
    namespace 'it.meditaly.app'
    compileSdk 36

    defaultConfig {
        applicationId 'it.meditaly.app'
        minSdk 29
        targetSdk 36
        versionCode 21
        versionName '0.5.1-beta2'
    }

    buildTypes {
        debug {
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'androidx.core:core:1.16.0'\n    implementation 'androidx.appcompat:appcompat:1.7.1'\n    implementation 'androidx.activity:activity:1.10.1'
    implementation platform('com.google.firebase:firebase-bom:34.19.0')
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
